name: manus-ci
on:
  push:
    branches:
      - main
      - '**'
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (scoped token, no creds persistentes)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --no-fund

      # Guard opcional: solo si ya tienes scripts/guard-vat.js
      - name: VAT/MwSt compliance guard
        run: |
          if [ -f scripts/guard-vat.js ]; then node scripts/guard-vat.js; else echo "guard-vat.js no encontrado, saltando"; fi

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps
        run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Run Playwright a11y (si existe)
        run: |
          if [ -f tests/a11y.spec.ts ]; then
            npx playwright install --with-deps
            npx playwright test tests/a11y.spec.ts
          else
            echo "a11y.spec.ts no encontrado, saltando"
          fi

