 name: manus-ci
 on:
   push:
     branches: [ main, "**" ]
   pull_request:
+permissions:
+  contents: write
+  pull-requests: write

 jobs:
   build:
     runs-on: ubuntu-latest
-    env:
-      GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
-      - uses: actions/checkout@v4
-      - name: GitHub CLI auth (no interactivo)
-        run: |
-          echo "$GH_TOKEN" | gh auth login --hostname github.com --with-token
-          gh auth status -h github.com
-      - name: Prueba de acceso al repo
-        run: |
-          git ls-remote https://x-access-token:${GH_TOKEN}@github.com/clouitreee/protech.git
+      - uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_TOKEN }}
+          persist-credentials: false
+
+      - name: gh status (sin login interactivo)
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          gh --version
+          gh auth status -h github.com || true
+
+      - name: Prueba de acceso al repo (git + token)
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          git ls-remote https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git >/dev/null
+
+      # …tus pasos de build/test aquí…
